- name: Agent installer
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: Create custom fact directory
    file:
      path: "/etc/ansible/facts.d"
      state: "directory"  
  - name: Creating custom control panel fact file
    copy:
      dest: "/etc/ansible/facts.d/controlpanel.fact"
      mode: 0755
      content: |
        #!/bin/bash
        CPANEL=`cat /usr/local/cpanel/version`
        PLESK=`cat /usr/local/psa/version`
        echo "[cpanel]"
        echo "version=${CPANEL}"
        echo "[plesk]"
        echo "version=${PLESK}"
  - name: Creating custom htaccess fact file
    copy:
      dest: "/etc/ansible/facts.d/htaccess.fact"
      mode: 0755
      content: |
        #!/bin/bash
        echo "[login]"
        echo "user=ansible"
        echo "password=16ef4c840068267820ccdce99c9b05b6079ca413b9e1d7982b15684034467729"        
  - name: Creates an entry cron job
    ansible.builtin.cron:
      name: "Create cron for agent"
      minute: "0"
      hour: "1"
      job: "perl -le 'sleep rand 9000' && ansible-pull -U https://github.com/uzzikie/ansible-agent > /dev/null"
